services:
  - type: web
    name: mk-earnings-demo-backend
    runtime: docker
    plan: free

    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

    envVars:
      - key: ADMIN_KEY
        sync: false

      - key: DB_FILE
        value: /var/data/mk_earnings.sqlite
